name: 'Terraform'

on:
  push:
    branches: [ "ansible" ]


permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ssh_host: ${{secrets.TF_VAR_host}}
      TF_VAR_ssh_port: ${{secrets.TF_VAR_port}}
      TF_VAR_ssh_user: ${{secrets.TF_VAR_user}}
      TF_VAR_ssh_pass: ${{secrets.TF_VAR_pass}}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible    

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
